import SplashScreen from './SplashScreen'
import SignIn from './SignIn'
import SignUp from './SignUp'
import SignUpAddress from './SignUpAddress'
import SuccessSignUp from './SuccessSignUp'
import Home from './Home'
import Profile from './Profile'
import Order from './Order'
import FoodDetail from './FoodDetail'
import OrderSummery from './OrderSummery'
import SuccessOrder from './SuccessOrder'
import OrderDetail from './OrderDetail'
export {SplashScreen,SignIn,SignUp,SignUpAddress,SuccessSignUp,SuccessOrder,Home,Profile,Order,FoodDetail,OrderDetail,OrderSummery}